version: '3'
services:
  postgresql:
    image: postgres:15
    environment:
      environment:
      POSTGRES_DB: catddit
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432

  cache:
    image: bitnami/redis:latest
    command: redis-server --requirepass pass
    restart: always
    ports:
      - 6379:6379
