version: '3'
services:
  postgresql:
    image: postgres:15
    environment:
      environment:
      POSTGRES_DB: group_chat
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432